version: "3"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - nifinet

  nifi01:
    image: apache/nifi:latest
    ports:
      - 6980:8080
    networks:
      - nifinet
    volumes:
      - C:/workspace/nifi/wayd-nifi/volume:/volume
    environment:
      - NIFI_WEB_HTTP_PORT=8080
#       - NIFI_CLUSTER_IS_NODE=true
#       - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_SENSITIVE_PROPS_KEY=asdfasdf11

networks:
  nifinet:
    driver: bridge