version: "3"
services:
    db:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "app"
            POSTGRES_PASSWORD: "pw"
        volumes:
            - D:/workspace/postgres/data:/var/lib/postgresql/data
            